---
title: "\"Finally\" kann nicht außerhalb einer Try-Anweisung verwendet werden."
ms.date: 07/20/2015
f1_keywords:
- vbc30382
- bc30382
helpviewer_keywords:
- BC30382
ms.assetid: 0314d8d2-18bc-4bbd-858c-0a18408b52fd
ms.openlocfilehash: 1d5987d6dc3b25088a55b6f0f43a8fb689f2c3e0
ms.sourcegitcommit: 558d78d2a68acd4c95ef23231c8b4e4c7bac3902
ms.translationtype: MT
ms.contentlocale: de-DE
ms.lasthandoff: 04/09/2019
ms.locfileid: "59306351"
---
# <a name="finally-cannot-appear-outside-a-try-statement"></a>"Finally" kann nicht außerhalb einer Try-Anweisung verwendet werden.
`Finally` wird zum Beenden eines `Try...Catch...Finally` -Blocks verwendet, kann daher nur einmal am Ende des Blocks angegeben werden. Entweder ist `Finally`unnötig, oder die `Finally` -Anweisung befindet sich außerhalb des entsprechenden `Try` -Blocks.  
  
 **Fehler-ID:** BC30382  
  
## <a name="to-correct-this-error"></a>So beheben Sie diesen Fehler  
  
1. Suchen und entfernen Sie die unnötige `Finally` -Anweisung.  
  
2. Verschieben Sie die `Finally` -Anweisung an die gewünschte Position im Code.  
  
## <a name="see-also"></a>Siehe auch

- [Try...Catch...Finally-Anweisung](../../visual-basic/language-reference/statements/try-catch-finally-statement.md)
